import type { Metadata } from "next";
import { Eczar } from "next/font/google";
import "./globals.css";
import Image from "next/image";

const ecazar = Eczar({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${ecazar.className} antialiased bg-[url('/backdrop.png')] bg-repeat w-full min-h-screen`}
        style={{ backgroundSize: "auto" }}
      >
        <div className="w-full min-h-screen max-w-pageMax">{children}</div>
      </body>
    </html>
  );
}
