import type { Metadata } from "next";
import { Eczar } from "next/font/google";
import "./globals.css";
import Image from "next/image";

const ecazar = Eczar({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${ecazar.className} antialiased`}>
        <div className="w-full h-[100svh] -z-10 fixed top-0 left-0 ">
          <Image
            className="object-cover"
            src="/backdrop.png"
            alt="Backdrop"
            fill
          />
        </div>
        {children}
      </body>
    </html>
  );
}
